Traceback (most recent call last):
  File "/nas/longleaf/home/ryzhou/Qamuy/ccpvdz_gamma_VQE_strong/test_sto_two_gamma_cas22.py", line 60, in <module>
    job=client.submit(input)
  File "/nas/longleaf/home/ryzhou/miniconda3/lib/python3.9/site-packages/qamuy/client/client.py", line 100, in submit
    validate_chemistry_inputs(input)
  File "/nas/longleaf/home/ryzhou/miniconda3/lib/python3.9/site-packages/qamuy_data_model/validators.py", line 119, in validate_chemistry_inputs
    validate_ansatz_target_system(**kwargs)
  File "/nas/longleaf/home/ryzhou/miniconda3/lib/python3.9/site-packages/qamuy_data_model/validators.py", line 385, in validate_ansatz_target_system
    raise QamuyValueError("depth is required")
qamuy_data_model.validators.QamuyValueError: depth is required
